const countryCodes = [
    { country: "India", code: "+91" },
    { country: "United States & CA", code: "+1" },
    { country: "United Kingdom", code: "+44" },
    { country: "Australia", code: "+61" },
    { country: "Germany", code: "+49" },
    { country: "France", code: "+33" },
    { country: "Italy", code: "+39" },
    { country: "Spain", code: "+34" },
    { country: "Russia", code: "+7" },
    { country: "China", code: "+86" },
    { country: "Japan", code: "+81" },
    { country: "South Korea", code: "+82" },
    { country: "Brazil", code: "+55" },
    { country: "Mexico", code: "+52" },
    { country: "South Africa", code: "+27" },
    { country: "United Arab Emirates", code: "+971" },
    { country: "Saudi Arabia", code: "+966" },
    { country: "Singapore", code: "+65" },
    { country: "New Zealand", code: "+64" },
    { country: "Pakistan", code: "+92" },
    { country: "Bangladesh", code: "+880" },
    { country: "Sri Lanka", code: "+94" },
    { country: "Nepal", code: "+977" },
    { country: "Indonesia", code: "+62" },
    { country: "Thailand", code: "+66" },
    { country: "Malaysia", code: "+60" },
    { country: "Philippines", code: "+63" },
    { country: "Vietnam", code: "+84" },
    { country: "Turkey", code: "+90" }
];

export default countryCodes;