import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/layout/navbar/Navbar";

import { Google_Sans_Flex } from "next/font/google"

const googleSansFlex = Google_Sans_Flex({
  subsets: ["latin"]
})



// const budujSans = localFont({
//   src: [
//     {
//       path: "../fonts/BudujSansTRIAL-Regular.ttf",
//       style: "normal",
//       weight: "400",
//     },
//     {
//       path: "../fonts/BudujSansTRIAL-Medium.ttf",
//       style: "normal",
//       weight: "500",
//     },
//     {
//       path: "../fonts/BudujSansTRIAL-Semibold.ttf",
//       style: "normal",
//       weight: "600",
//     },
//     {
//       path: "../fonts/BudujSansTRIAL-Bold.ttf",
//       style: "normal",
//       weight: "700",
//     },

//   ],
// })
export const metadata: Metadata = {
  title: "SP Mech",
  description: "Generated by create next app ",
};
import LenisProvider from "@/components/providers/LenisProvider";
import Footer from "@/components/layout/Footer";
import QueryClientProviderFile from "@/components/providers/QueryClientProviderFile";
import CategoriesProvider from "@/components/providers/CategoriesProvider";
import { Toaster } from "sonner";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${googleSansFlex.className} antialiased`}
      >

        <QueryClientProviderFile>
          <CategoriesProvider>
            <LenisProvider>

              <Toaster position="top-center" richColors />
              <Navbar />
              <div className="main" id="main">
                {children}
                <Footer />
              </div>
            </LenisProvider>
          </CategoriesProvider>
        </QueryClientProviderFile>
      </body>
    </html>
  );
}
